[book]
authors = ["The LabDaemon Team"]
language = "en"
multilingual = false
src = "src"
title = "LabDaemon Documentation"

[output.html]
git-repository-url = "https://github.com/qnslab/labdaemon"
mathjax-support = true
